/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitterclient;


import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import twitter4j.Status;
import twitter4j.TwitterException;


/**
 *
 * @author Caleb Norris
 */
public class TwitterJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TwitterJFrame and initializes arrays.
     */
    public TwitterJFrame() {
        twitterList = new ArrayList<>();
        accountMap = new HashMap<>();
        checkChecked = new ArrayList<>();
        mediaUrlList = new ArrayList<>();
        currentUsers = new ArrayList<>();
        userLabels = new ArrayList<>();
        homeLabels = new ArrayList<>();
        likeButtons = new ArrayList<>();
        retweetButtons = new ArrayList<>();
        facebookUserLabels = new ArrayList<>();
        facebookList = new ArrayList<>();
        checkCheckedFacebook = new ArrayList<>();
        facebookAccountMap = new HashMap<>();
        initComponents();
     
        twitterComboBox.removeAllItems();
        facebookComboBox.removeAllItems();
        TwitterUserFeed.setLayout(new BoxLayout(TwitterUserFeed, 
                BoxLayout.Y_AXIS));
        TwitterHomeFeed.setLayout(new BoxLayout(TwitterHomeFeed, 
                BoxLayout.Y_AXIS));
        facebookUserFeed.setLayout(new BoxLayout(facebookUserFeed, 
                BoxLayout.Y_AXIS));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        postButton = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        twitterComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TwitterUserFeed = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TwitterHomeFeed = new javax.swing.JPanel();
        FacebookScrollPane = new javax.swing.JScrollPane();
        facebookUserFeed = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        facebookComboBox = new javax.swing.JComboBox<>();
        facebookPostButton = new javax.swing.JButton();
        facebookLoginTest = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        chooseTwitterAccounts = new javax.swing.JMenu();
        facebookAccountsForPost = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Login.setText("Twitter Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Your Twitter Posts:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        postButton.setText("Post Twitter");
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });

        twitterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        twitterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Your Twitter Feed:");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(750, 265));

        javax.swing.GroupLayout TwitterUserFeedLayout = new javax.swing.GroupLayout(TwitterUserFeed);
        TwitterUserFeed.setLayout(TwitterUserFeedLayout);
        TwitterUserFeedLayout.setHorizontalGroup(
            TwitterUserFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        TwitterUserFeedLayout.setVerticalGroup(
            TwitterUserFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(TwitterUserFeed);

        javax.swing.GroupLayout TwitterHomeFeedLayout = new javax.swing.GroupLayout(TwitterHomeFeed);
        TwitterHomeFeed.setLayout(TwitterHomeFeedLayout);
        TwitterHomeFeedLayout.setHorizontalGroup(
            TwitterHomeFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        TwitterHomeFeedLayout.setVerticalGroup(
            TwitterHomeFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(TwitterHomeFeed);

        javax.swing.GroupLayout facebookUserFeedLayout = new javax.swing.GroupLayout(facebookUserFeed);
        facebookUserFeed.setLayout(facebookUserFeedLayout);
        facebookUserFeedLayout.setHorizontalGroup(
            facebookUserFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        facebookUserFeedLayout.setVerticalGroup(
            facebookUserFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );

        FacebookScrollPane.setViewportView(facebookUserFeed);

        jLabel3.setText("Your Facebook Posts:");

        facebookComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        facebookComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookComboBoxActionPerformed(evt);
            }
        });

        facebookPostButton.setText("Post Facebook");
        facebookPostButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookPostButtonActionPerformed(evt);
            }
        });

        facebookLoginTest.setText("Facebook Login");
        facebookLoginTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookLoginTestActionPerformed(evt);
            }
        });

        chooseTwitterAccounts.setText("Choose Accounts for Twitter");
        jMenuBar1.add(chooseTwitterAccounts);

        facebookAccountsForPost.setText("| Choose Accounts for Facebook");
        jMenuBar1.add(facebookAccountsForPost);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Login)
                            .addComponent(postButton)))
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addComponent(jLabel3))
                    .addComponent(twitterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(facebookLoginTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(facebookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FacebookScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(facebookPostButton))
                        .addGap(0, 45, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twitterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login)
                    .addComponent(facebookComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facebookLoginTest))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(postButton)
                                    .addComponent(facebookPostButton))
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FacebookScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(189, 189, 189)))
                .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
        Creates twitter login object and gets authorization for actions.
        Gets and calls to show the feed of the new user.
        Populates the twitter combobox and the twitter account menu.
    */
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        twitter = new TwitterLogIn();
        
        twitter.auth();
        try 
        {
            twitter.createStatusLabels();
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.
                    SEVERE, null, ex);
        }
        
        
        try 
        {
            username = twitter.getUsername();
            emptyFeeds();
            showFeed(twitter);
            twitterList.add(twitter);
            accountMap.put(username, counter);
            twitterComboBox.addItem(username);
            twitterComboBox.setSelectedItem(username);
            ItemListener itemListener = new ItemListener()
            {
                public void itemStateChanged(ItemEvent itemEvent)
                {
                    try {
                        emptyFeeds();
                        showFeed(twitterList.get(accountMap.get(itemEvent.
                                getItem())));
                    } catch (IOException ex) {
                        Logger.getLogger(TwitterJFrame.class.getName()).
                                log(Level.SEVERE, null, ex);
                    }
                }
            };
            twitterComboBox.addItemListener(itemListener);
            javax.swing.JCheckBoxMenuItem checkbox = new javax.swing.
                    JCheckBoxMenuItem(username);
            chooseTwitterAccounts.add(checkbox);
            checkChecked.add(checkbox);
            checkCounter++;
        } 
        catch (TwitterException | IOException ex) 
        {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.
                    SEVERE, null, ex);
        }
        
        counter++;
            
        
    }//GEN-LAST:event_LoginActionPerformed

    /*
        Handles the post button action to post user input to all selected user's accounts.
    */
    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        // TODO add your handling code here:
        toPost = JOptionPane.showInputDialog("Please type what you want to "
                + "post (Below 281 characters): ");
        if(toPost.length() < 281)
        {
            int counter2 = 0;
            for(int i = 0; i < checkCounter; i++)
            {
                if(checkChecked.get(i).getState() == true)
                {
                    toPost = toPost + ".";
                    try 
                    {
                        twitterList.get(i).makePost(toPost);
                        twitterList.get(i).setStatus();
                        twitterList.get(i).createStatusLabels();
                    } 
                    catch (TwitterException | IOException ex) 
                    {
                        Logger.getLogger(TwitterJFrame.class.getName()).
                                log(Level.SEVERE, null, ex);
                    }
                    counter2++;
                }
            }
            if(counter2 > 0)
            {
                JOptionPane.showMessageDialog(null, "Your post was a success!");
                try {
                    emptyFeeds();
                    showFeed(twitterList.get(0));
                } catch (IOException ex) {
                    Logger.getLogger(TwitterJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "You haven't selected any accounts.");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Post failed. Must be less"
                    + " than 281 characters.");
        }
    }//GEN-LAST:event_postButtonActionPerformed

    private void twitterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterComboBoxActionPerformed
        
    }//GEN-LAST:event_twitterComboBoxActionPerformed

    private void facebookComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facebookComboBoxActionPerformed

    /*
        Facebook posting testing
    */
    private void facebookPostButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookPostButtonActionPerformed
        // TODO add your handling code here:
        
        //toPost = JOptionPane.showInputDialog("Please type what you "
        //        + "want to post: ");
        for(int i = 0; i < checkFacebookCounter; i++)
        {
            if(checkCheckedFacebook.get(i).getState() == true)
            {
                //toPost = toPost + ".";
                facebookList.get(i).makePost();
            }
        }
        
    }//GEN-LAST:event_facebookPostButtonActionPerformed

    /*
        Facebook Login Testing
    */
    private void facebookLoginTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookLoginTestActionPerformed
        // TODO add your handling code here:
        FacebookTestLogin facebook = new FacebookTestLogin();
   
        try {
            facebook.loginPlease();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(TwitterJFrame.class.getName()).log(Level.
                    SEVERE, null, ex);
        }
        
        facebook.facebookStuff();
        facebook.facebookLabels();
        facebookList.add(facebook);
        facebookAccountMap.put(facebook.getUsername(), facebookCounter);
        facebookComboBox.addItem(facebook.getUsername());
        facebookComboBox.setSelectedItem(facebook.getUsername());
        ItemListener itemListener = new ItemListener()
        {
            public void itemStateChanged(ItemEvent itemEvent)
            {
                emptyFacebookFeeds();
                facebookUserLabels = facebookList.get(facebookAccountMap.
                        get(itemEvent.
                        getItem())).getUserLabels();
                for(JLabel label: facebookUserLabels)
                {
                    facebookUserFeed.add(label);
                }
            }
        };
        facebookComboBox.addItemListener(itemListener);
        javax.swing.JCheckBoxMenuItem checkbox = new javax.swing.
                JCheckBoxMenuItem(facebook.getUsername());
        facebookAccountsForPost.add(checkbox);
        checkCheckedFacebook.add(checkbox);
        checkFacebookCounter++;
        facebookUserLabels = facebook.getUserLabels();
        emptyFacebookFeeds();
        for(JLabel label: facebookUserLabels)
        {
            facebookUserFeed.add(label);
        }
        facebookCounter++;
    }//GEN-LAST:event_facebookLoginTestActionPerformed

    /*
        Gets the labels to be used for the Twitter Feeds and
        puts them onto the two left most panels.
    */
    public void showFeed(TwitterLogIn tli) throws IOException
    {
        userLabels = tli.getUserLabels();
        homeLabels = tli.getHomeLabels();
        likeButtons = tli.getLikeButtons();
        retweetButtons = tli.getRetweetButtons();
        status1 = tli.getStatus1();
        status2 = tli.getStatus2();
        
        
        for(JLabel label: userLabels)
        {
            TwitterUserFeed.add(label);
        }
        for(int i = 0; i < homeLabels.size(); i++)
        {
            TwitterHomeFeed.add(homeLabels.get(i));
            Status stat = status2.get(i);
            likeButtons.get(i).addActionListener(new java.awt.event.
                    ActionListener() 
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) 
                {
                    if(stat.isFavorited() == false)
                    {
                        for(int i = 0; i < checkCounter; i++)
                        {               
                            if(checkChecked.get(i).getState() == true)
                            {
                                try 
                                {
                                    twitterList.get(i).createLike(stat.getId());
                                    JOptionPane.showMessageDialog(null,
                                            "This post has been liked.");
                                } 
                                catch (TwitterException ex) 
                                {
                                    Logger.getLogger(TwitterJFrame.class.
                                            getName()).
                                            log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    }
                    else
                    {
                        try {
                            tli.unlikePost(stat.getId());
                        } catch (TwitterException ex) {
                            Logger.getLogger(TwitterJFrame.class.getName()).
                                    log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null,
                                "This post has been unliked.");
                    }
                }
            });
            TwitterHomeFeed.add(likeButtons.get(i));
            retweetButtons.get(i).addActionListener(new java.awt.event.
                    ActionListener() 
            {
                public void actionPerformed(java.awt.event.ActionEvent evt) 
                {
                    if(stat.isRetweetedByMe() == false)
                    {
                        for(int i = 0; i < checkCounter; i++)
                        {               
                            if(checkChecked.get(i).getState() == true)
                            {
                                try 
                                {
                                    twitterList.get(i).retweet(stat.getId());
                                    JOptionPane.showMessageDialog(null,
                                            "This post has been retweeted.");
                                } 
                                catch (TwitterException ex) 
                                {
                                    Logger.getLogger(TwitterJFrame.class.
                                            getName()).
                                            log(Level.SEVERE, null, ex);
                                }
                            }
                        }
                    }
                    else
                    {
                        try {
                            tli.unlikePost(stat.getId());
                        } catch (TwitterException ex) {
                            Logger.getLogger(TwitterJFrame.class.getName()).
                                    log(Level.SEVERE, null, ex);
                        }
                        JOptionPane.showMessageDialog(null,
                                "This post has been unretweeted.");
                    }
                }
            });
            TwitterHomeFeed.add(retweetButtons.get(i));
        }
      
        TwitterHomeFeed.revalidate();
        TwitterHomeFeed.repaint();
    }
    
    /*
        Empties the twitter feeds.
    */
    public void emptyFeeds()
    {
        TwitterUserFeed.removeAll();
        TwitterUserFeed.revalidate();
        TwitterUserFeed.repaint();
        TwitterHomeFeed.removeAll();
        TwitterHomeFeed.revalidate();
        TwitterHomeFeed.repaint();
    }
    
    /*
        Empties the facebook feeds.
    */
    public void emptyFacebookFeeds()
    {
        facebookUserFeed.removeAll();
        facebookUserFeed.revalidate();
        facebookUserFeed.repaint();
    }
    
    /*
        Adds the given user's name to the list currentUsers
    */
    public void addToCurrentUsersArray(String str)
    {
        currentUsers.add(str);
    }
    
    /*
        Chekcs if the current user arrau contains a user.
    */
    public boolean checkCurrentUserArray(String str)
    {
        return currentUsers.contains(str);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new TwitterJFrame().setVisible(true);
            }
        });
        
    }

    private TwitterLogIn twitter;
    private ArrayList<TwitterLogIn> twitterList;
    private HashMap<String, Integer> accountMap;
    private int counter = 0;
    private String username;
    private ArrayList<javax.swing.JCheckBoxMenuItem> checkChecked;
    private ArrayList<javax.swing.JCheckBoxMenuItem> checkCheckedFacebook;
    private int checkCounter = 0;
    private int checkFacebookCounter = 0;
    private String toPost = "";
    private ArrayList<String> mediaUrlList;
    private ArrayList<String> currentUsers;
    private ArrayList<JLabel> userLabels;
    private ArrayList<JLabel> homeLabels;
    private ArrayList<JButton> likeButtons;
    private ArrayList<JButton> retweetButtons;
    private ArrayList<JLabel> facebookUserLabels;
    private ArrayList<FacebookTestLogin> facebookList;
    private List<Status> status2;
    private List<Status> status1;
    private HashMap<String, Integer> facebookAccountMap;
    private int facebookCounter = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane FacebookScrollPane;
    private javax.swing.JButton Login;
    private javax.swing.JPanel TwitterHomeFeed;
    private javax.swing.JPanel TwitterUserFeed;
    private java.awt.Canvas canvas1;
    private javax.swing.JMenu chooseTwitterAccounts;
    private javax.swing.JMenu facebookAccountsForPost;
    private javax.swing.JComboBox<String> facebookComboBox;
    private javax.swing.JButton facebookLoginTest;
    private javax.swing.JButton facebookPostButton;
    private javax.swing.JPanel facebookUserFeed;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton postButton;
    private javax.swing.JComboBox<String> twitterComboBox;
    // End of variables declaration//GEN-END:variables
}
